name: amap_location_quick_example
description: Demonstrates how to use the amap_location_quick plugin.

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  amap_location_quick:
    path: ../
  cupertino_icons: ^1.0.2
  #####################################################################
  # 权限请求
  permission_handler: ">=8.0.0 <9.0.0"
  # 提示弹窗
  bot_toast: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
